# -*- coding: utf-8 -*-
# 本文件由 scripts/_emit.py 从 data/entries.json 生成（仅元数据）。
# 正文长文集中在 scripts/bodies.py 的 BODIES 字典中，便于逐篇维护。
import json, collections
from bodies import BODIES, EXTRA, EXTRA2
from bodies_extra3 import EXTRA3
from bodies_hanzi import BODIES as _B_HZ
from bodies_jiesu import BODIES as _B_JS
from bodies_yishu import BODIES as _B_YS
from bodies_liyi import BODIES as _B_LY
from bodies_yiyao import BODIES as _B_YY
from bodies_keji import BODIES as _B_KJ
from bodies_dili import BODIES as _B_DL
for _b in (_B_HZ, _B_JS, _B_YS, _B_LY, _B_YY, _B_KJ, _B_DL):
    BODIES.update(_b)

# 合并所有补文层（BODIES + EXTRA + EXTRA2 + EXTRA3）为完整正文，段落间以空行分隔；
# 合并后清空分层字典，使下方 E() 调用只读取已合并的 BODIES。
for _cid in set(list(BODIES) + list(EXTRA) + list(EXTRA2) + list(EXTRA3)):
    _parts = [BODIES.get(_cid, ""), EXTRA.get(_cid, ""), EXTRA2.get(_cid, ""), EXTRA3.get(_cid, "")]
    _full = "\n\n".join(p for p in _parts if p).strip()
    if _full:
        BODIES[_cid] = _full
EXTRA = {}; EXTRA2 = {}; EXTRA3 = {}
import json as _json
_OLD = {e["id"]: e["body"] for e in _json.load(open("data/entries.json", encoding="utf-8"))["entries"]}

entries = []


def E(id, title, domain, sub, summary, body, classic, art, tags):
    entries.append({
        "id": id, "title": title, "domain": domain, "sub": sub,
        "summary": summary, "body": body, "classic": classic,
        "art": art, "tags": tags,
    })


def C(lib, i):
    return [{"lib": lib, "id": i}]

def CH(ch, seal=False):
    return {"type": "character", "params": {"char": ch, "seal": seal}}

def OB(kind, label=None):
    return {"type": "object", "params": {"kind": kind, "label": label}}

def ST(term, icon, season):
    return {"type": "solar-term", "params": {"term": term, "icon": icon, "season": season}}


# ============ 以下为各条目元数据（正文见 bodies.py） ============

E('sixiang-rujia', "儒家", "思想哲学", "儒家", "以仁为本、以礼为纲，中国人安身立命的底色。", ((BODIES.get("sixiang-rujia", "") + EXTRA.get("sixiang-rujia", "") + EXTRA2.get("sixiang-rujia", "")) or _OLD.get("sixiang-rujia", "")), [{'lib': '论语', 'id': 'lunyu-20'}], {'type': 'character', 'params': {'char': '仁', 'seal': False}}, ['儒家', '论语', '历史', '闯关'])
E('sixiang-daojia', "道家与道教", "思想哲学", "道家·道教", "道法自然、清静无为，另一条安顿生命的路。", ((BODIES.get("sixiang-daojia", "") + EXTRA.get("sixiang-daojia", "") + EXTRA2.get("sixiang-daojia", "")) or _OLD.get("sixiang-daojia", "")), [{'lib': '道德经', 'id': 'ddj-25'}], {'type': 'character', 'params': {'char': '道', 'seal': False}}, ['道家', '道教', '历史'])
E('sixiang-fojia', "中国佛教", "思想哲学", "佛家", "自西徂东，落地生根，化为中国思想的一脉。", ((BODIES.get("sixiang-fojia", "") + EXTRA.get("sixiang-fojia", "") + EXTRA2.get("sixiang-fojia", "")) or _OLD.get("sixiang-fojia", "")), [{'lib': '六祖坛经', 'id': 'zc-1'}], {'type': 'character', 'params': {'char': '佛', 'seal': False}}, ['佛家', '历史', '闯关'])
E('classic-lunyu', "《论语》", "思想哲学", "经典原文", "半部可治天下，一句足醒平生。", ((BODIES.get("classic-lunyu", "") + EXTRA.get("classic-lunyu", "") + EXTRA2.get("classic-lunyu", "")) or _OLD.get("classic-lunyu", "")), [{'lib': '论语', 'id': 'lunyu-16'}], {'type': 'character', 'params': {'char': '论', 'seal': False}}, ['论语', '经典', '历史'])
E('sixiang-zhongyong', "中庸", "思想哲学", "儒家", "不偏不倚，无过无不及，中国人的尺度智慧。", ((BODIES.get("sixiang-zhongyong", "") + EXTRA.get("sixiang-zhongyong", "") + EXTRA2.get("sixiang-zhongyong", "")) or _OLD.get("sixiang-zhongyong", "")), [{'lib': '中庸', 'id': 'zy-1'}], {'type': 'character', 'params': {'char': '中', 'seal': False}}, ['儒家', '经典', '历史'])
E('sixiang-mengzi', "孟子", "思想哲学", "儒家", "养浩然之气，倡仁政民本，儒家“亚圣”。", ((BODIES.get("sixiang-mengzi", "") + EXTRA.get("sixiang-mengzi", "") + EXTRA2.get("sixiang-mengzi", "")) or _OLD.get("sixiang-mengzi", "")), [{'lib': '孟子', 'id': 'mengzi-1'}], {'type': 'character', 'params': {'char': '孟', 'seal': False}}, ['儒家', '孟子', '历史'])
E('sixiang-zhuangzi', "庄子", "思想哲学", "道家·道教", "逍遥于物外，齐物于心中，道家的诗意极境。", ((BODIES.get("sixiang-zhuangzi", "") + EXTRA.get("sixiang-zhuangzi", "") + EXTRA2.get("sixiang-zhuangzi", "")) or _OLD.get("sixiang-zhuangzi", "")), [{'lib': '庄子', 'id': 'zhuangzi-2'}], {'type': 'character', 'params': {'char': '庄', 'seal': False}}, ['道家', '庄子', '历史'])
E('classic-daodejing', "《道德经》", "思想哲学", "经典原文", "五千言，藏天下至理；一个“道”，说尽玄机。", ((BODIES.get("classic-daodejing", "") + EXTRA.get("classic-daodejing", "") + EXTRA2.get("classic-daodejing", "")) or _OLD.get("classic-daodejing", "")), [{'lib': '道德经', 'id': 'ddj-8'}], {'type': 'character', 'params': {'char': '德', 'seal': False}}, ['道家', '经典', '历史'])
E('classic-daxue', "《大学》", "思想哲学", "经典原文", "三纲八目，修齐治平，儒者的路线图。", ((BODIES.get("classic-daxue", "") + EXTRA.get("classic-daxue", "") + EXTRA2.get("classic-daxue", "")) or _OLD.get("classic-daxue", "")), [{'lib': '四书章句', 'id': 'sishu-1'}], {'type': 'character', 'params': {'char': '学', 'seal': False}}, ['儒家', '经典', '历史'])
E('sixiang-yinyang', "阴阳五行", "思想哲学", "通识", "中国人的宇宙语法，万事万物的说明书。", ((BODIES.get("sixiang-yinyang", "") + EXTRA.get("sixiang-yinyang", "") + EXTRA2.get("sixiang-yinyang", "")) or _OLD.get("sixiang-yinyang", "")), [{'lib': '易经', 'id': 'yj-1'}], {'type': 'character', 'params': {'char': '阴', 'seal': False}}, ['阴阳', '五行', '历史'])
E('sixiang-xunzi', "荀子", "思想哲学", "儒家", "性恶而言善，礼法并施，儒家的另一脉。", ((BODIES.get("sixiang-xunzi", "") + EXTRA.get("sixiang-xunzi", "") + EXTRA2.get("sixiang-xunzi", "")) or _OLD.get("sixiang-xunzi", "")), [{'lib': '荀子', 'id': 'xunzi-1'}], {'type': 'character', 'params': {'char': '荀', 'seal': False}}, ['儒家', '荀子', '历史'])
E('sixiang-mojia', "墨家", "思想哲学", "墨家", "兼爱非攻、尚贤节用，平民的侠义理想。", ((BODIES.get("sixiang-mojia", "") + EXTRA.get("sixiang-mojia", "") + EXTRA2.get("sixiang-mojia", "")) or _OLD.get("sixiang-mojia", "")), [{'lib': '墨子', 'id': 'mozi-1'}], {'type': 'character', 'params': {'char': '墨', 'seal': False}}, ['墨家', '历史'])
E('sixiang-fajia', "法家", "思想哲学", "法家", "不别亲疏、不殊贵贱，一断于法。", ((BODIES.get("sixiang-fajia", "") + EXTRA.get("sixiang-fajia", "") + EXTRA2.get("sixiang-fajia", "")) or _OLD.get("sixiang-fajia", "")), [{'lib': '韩非子', 'id': 'hz-2'}], {'type': 'character', 'params': {'char': '法', 'seal': False}}, ['法家', '历史'])
E('sixiang-lizhu', "程朱理学", "思想哲学", "理学", "存天理、穷义理，儒家的哲学化高峰。", ((BODIES.get("sixiang-lizhu", "") + EXTRA.get("sixiang-lizhu", "") + EXTRA2.get("sixiang-lizhu", "")) or _OLD.get("sixiang-lizhu", "")), [{'lib': '中庸', 'id': 'zy-3'}], {'type': 'character', 'params': {'char': '理', 'seal': False}}, ['理学', '儒家', '历史'])
E('sixiang-xinxue', "陆王心学", "思想哲学", "心学", "心即理、知行合一，一盏向内点亮的光。", ((BODIES.get("sixiang-xinxue", "") + EXTRA.get("sixiang-xinxue", "") + EXTRA2.get("sixiang-xinxue", "")) or _OLD.get("sixiang-xinxue", "")), [{'lib': '传习录', 'id': 'czl-1'}], {'type': 'character', 'params': {'char': '心', 'seal': False}}, ['心学', '儒家', '历史'])
E('sixiang-xuanxue', "魏晋玄学", "思想哲学", "玄学", "辨名析理、越名任心，乱世里的清谈与风流。", ((BODIES.get("sixiang-xuanxue", "") + EXTRA.get("sixiang-xuanxue", "") + EXTRA2.get("sixiang-xuanxue", "")) or _OLD.get("sixiang-xuanxue", "")), [{'lib': '易经', 'id': 'yj-3'}], {'type': 'character', 'params': {'char': '玄', 'seal': False}}, ['玄学', '道家', '历史'])
E('sixiang-dongzhongshu', "董仲舒与独尊儒术", "思想哲学", "儒家", "罢黜百家、独尊儒术，儒家登上正统之位。", ((BODIES.get("sixiang-dongzhongshu", "") + EXTRA.get("sixiang-dongzhongshu", "") + EXTRA2.get("sixiang-dongzhongshu", "")) or _OLD.get("sixiang-dongzhongshu", "")), [{'lib': '春秋繁露', 'id': 'czfl-1'}], {'type': 'character', 'params': {'char': '董', 'seal': False}}, ['儒家', '汉', '历史'])
E('sixiang-yijing', "易学与象数", "思想哲学", "通识", "群经之首，穷理尽性，开物成务。", ((BODIES.get("sixiang-yijing", "") + EXTRA.get("sixiang-yijing", "") + EXTRA2.get("sixiang-yijing", "")) or _OLD.get("sixiang-yijing", "")), [{'lib': '易经', 'id': 'yj-2'}], {'type': 'character', 'params': {'char': '易', 'seal': False}}, ['易经', '阴阳', '历史'])
E('lishi-qin', "秦：中央集权之始", "历史脉络", "朝代变迁", "三公九卿、郡县天下，两千年帝制的模板。", ((BODIES.get("lishi-qin", "") + EXTRA.get("lishi-qin", "") + EXTRA2.get("lishi-qin", "")) or _OLD.get("lishi-qin", "")), [{'lib': '韩非子', 'id': 'hz-1'}], {'type': 'character', 'params': {'char': '秦', 'seal': False}}, ['历史', '朝代', '秦', '官制'])
E('lishi-han', "汉：大一统的定型", "历史脉络", "朝代变迁", "郡国并行到独尊儒术，奠定华夏筋骨。", ((BODIES.get("lishi-han", "") + EXTRA.get("lishi-han", "") + EXTRA2.get("lishi-han", "")) or _OLD.get("lishi-han", "")), [{'lib': '史记', 'id': 'shiji-1'}], {'type': 'character', 'params': {'char': '汉', 'seal': False}}, ['历史', '朝代', '汉'])
E('lishi-tang', "唐：盛世与开放", "历史脉络", "朝代变迁", "三省六部、科举仕进，长安城里的世界中心。", ((BODIES.get("lishi-tang", "") + EXTRA.get("lishi-tang", "") + EXTRA2.get("lishi-tang", "")) or _OLD.get("lishi-tang", "")), [{'lib': '资治通鉴', 'id': 'zztj-1'}], {'type': 'character', 'params': {'char': '唐', 'seal': False}}, ['历史', '朝代', '唐'])
E('lishi-song', "宋：文人政治与近世", "历史脉络", "朝代变迁", "重文轻武、科举鼎盛，中国的“文艺复兴”。", ((BODIES.get("lishi-song", "") + EXTRA.get("lishi-song", "") + EXTRA2.get("lishi-song", "")) or _OLD.get("lishi-song", "")), [{'lib': '资治通鉴', 'id': 'zztj-2'}], {'type': 'character', 'params': {'char': '宋', 'seal': False}}, ['历史', '朝代', '宋'])
E('lishi-yuan', "元：行省与一统", "历史脉络", "朝代变迁", "草原入主，行省建制，版图空前辽阔。", ((BODIES.get("lishi-yuan", "") + EXTRA.get("lishi-yuan", "") + EXTRA2.get("lishi-yuan", "")) or _OLD.get("lishi-yuan", "")), [{'lib': '易经', 'id': 'yj-3'}], {'type': 'character', 'params': {'char': '元', 'seal': False}}, ['历史', '朝代', '元'])
E('lishi-ming', "明：内阁与专制顶峰", "历史脉络", "朝代变迁", "废丞相、设内阁，皇权直抵云霄。", ((BODIES.get("lishi-ming", "") + EXTRA.get("lishi-ming", "") + EXTRA2.get("lishi-ming", "")) or _OLD.get("lishi-ming", "")), [{'lib': '传习录', 'id': 'czl-1'}], {'type': 'character', 'params': {'char': '明', 'seal': False}}, ['历史', '朝代', '明'])
E('lishi-qing', "清：军机处与末世", "历史脉络", "朝代变迁", "满汉共治、军机揽权，帝制的回光与落幕。", ((BODIES.get("lishi-qing", "") + EXTRA.get("lishi-qing", "") + EXTRA2.get("lishi-qing", "")) or _OLD.get("lishi-qing", "")), [{'lib': '资治通鉴', 'id': 'zztj-1'}], {'type': 'character', 'params': {'char': '清', 'seal': False}}, ['历史', '朝代', '清'])
E('lishi-sansheng', "三省六部制", "历史脉络", "典章制度", "中书出令、门下封驳、尚书执行，最早的权力制衡。", ((BODIES.get("lishi-sansheng", "") + EXTRA.get("lishi-sansheng", "") + EXTRA2.get("lishi-sansheng", "")) or _OLD.get("lishi-sansheng", "")), [{'lib': '周礼', 'id': 'zl-1'}], {'type': 'character', 'params': {'char': '官', 'seal': False}}, ['历史', '朝代', '官制'])
E('lishi-keju', "科举制", "历史脉络", "典章制度", "打破门第、以文取士，古代最重大的制度发明。", ((BODIES.get("lishi-keju", "") + EXTRA.get("lishi-keju", "") + EXTRA2.get("lishi-keju", "")) or _OLD.get("lishi-keju", "")), [{'lib': '荀子', 'id': 'xunzi-2'}], {'type': 'character', 'params': {'char': '举', 'seal': False}}, ['历史', '朝代', '科举'])
E('lishi-jiancha', "监察与谏官", "历史脉络", "典章制度", "御史纠弹、谏官封驳，皇权的自我纠错机制。", ((BODIES.get("lishi-jiancha", "") + EXTRA.get("lishi-jiancha", "") + EXTRA2.get("lishi-jiancha", "")) or _OLD.get("lishi-jiancha", "")), [{'lib': '周礼', 'id': 'zl-1'}], {'type': 'character', 'params': {'char': '察', 'seal': False}}, ['历史', '朝代', '官制'])
E('lishi-fenjun', "分封与郡县", "历史脉络", "典章制度", "封建与郡县之争，贯穿两千年的一条暗线。", ((BODIES.get("lishi-fenjun", "") + EXTRA.get("lishi-fenjun", "") + EXTRA2.get("lishi-fenjun", "")) or _OLD.get("lishi-fenjun", "")), [{'lib': '史记', 'id': 'shiji-2'}], {'type': 'character', 'params': {'char': '封', 'seal': False}}, ['历史', '朝代', '官制'])
E('lishi-zaixiang', "宰相制度演变", "历史脉络", "典章制度", "从三公到内阁，一个职位的两千年退场。", ((BODIES.get("lishi-zaixiang", "") + EXTRA.get("lishi-zaixiang", "") + EXTRA2.get("lishi-zaixiang", "")) or _OLD.get("lishi-zaixiang", "")), [{'lib': '韩非子', 'id': 'hz-1'}], {'type': 'character', 'params': {'char': '相', 'seal': False}}, ['历史', '朝代', '官制'])
E('lishi-ganzhi', "干支与历法", "历史脉络", "典章制度", "十天干十二地支，中国人的时间密码。", ((BODIES.get("lishi-ganzhi", "") + EXTRA.get("lishi-ganzhi", "") + EXTRA2.get("lishi-ganzhi", "")) or _OLD.get("lishi-ganzhi", "")), [{'lib': '千字文', 'id': 'qz-2'}], {'type': 'character', 'params': {'char': '历', 'seal': False}}, ['历史', '历法', '节气'])
E('lishi-sichou', "丝绸之路", "历史脉络", "重大事件", "一条商路，连起欧亚大陆的文明血脉。", ((BODIES.get("lishi-sichou", "") + EXTRA.get("lishi-sichou", "") + EXTRA2.get("lishi-sichou", "")) or _OLD.get("lishi-sichou", "")), [{'lib': '易经', 'id': 'yj-2'}], {'type': 'character', 'params': {'char': '丝', 'seal': False}}, ['历史', '朝代', '丝路'])
E('lishi-sida', "四大发明", "历史脉络", "重大事件", "造纸印刷火药指南针，改变世界的中国创造。", ((BODIES.get("lishi-sida", "") + EXTRA.get("lishi-sida", "") + EXTRA2.get("lishi-sida", "")) or _OLD.get("lishi-sida", "")), [{'lib': '梦溪笔谈', 'id': 'mxt-1'}], {'type': 'character', 'params': {'char': '器', 'seal': False}}, ['历史', '朝代', '发明'])
E('lishi-changcheng', "长城", "历史脉络", "重大事件", "蜿蜒万里的边界，也是文明的隐喻。", ((BODIES.get("lishi-changcheng", "") + EXTRA.get("lishi-changcheng", "") + EXTRA2.get("lishi-changcheng", "")) or _OLD.get("lishi-changcheng", "")), None, {'type': 'character', 'params': {'char': '城', 'seal': False}}, ['历史', '朝代', '长城'])
E('lishi-zhenghe', "郑和下西洋", "历史脉络", "重大事件", "宝船七下西洋，和平交往的蓝色壮举。", ((BODIES.get("lishi-zhenghe", "") + EXTRA.get("lishi-zhenghe", "") + EXTRA2.get("lishi-zhenghe", "")) or _OLD.get("lishi-zhenghe", "")), [{'lib': '楚辞', 'id': 'chuci-01'}], {'type': 'character', 'params': {'char': '航', 'seal': False}}, ['历史', '朝代', '明', '航海'])
E('lishi-weijin', "魏晋南北朝", "历史脉络", "朝代变迁", "门阀政治、民族融合，乱世里的解体与重生。", ((BODIES.get("lishi-weijin", "") + EXTRA.get("lishi-weijin", "") + EXTRA2.get("lishi-weijin", "")) or _OLD.get("lishi-weijin", "")), [{'lib': '易经', 'id': 'yj-3'}], {'type': 'character', 'params': {'char': '魏', 'seal': False}}, ['历史', '朝代', '魏晋'])
E('lishi-chunqiu', "春秋战国", "历史脉络", "朝代变迁", "礼崩乐坏、百家争鸣，中华文明的奠基时代。", ((BODIES.get("lishi-chunqiu", "") + EXTRA.get("lishi-chunqiu", "") + EXTRA2.get("lishi-chunqiu", "")) or _OLD.get("lishi-chunqiu", "")), [{'lib': '孟子', 'id': 'mengzi-4'}], {'type': 'character', 'params': {'char': '周', 'seal': False}}, ['历史', '朝代', '春秋'])
E('classic-shijing', "《诗经》", "汉字·文学", "经典原文", "三百篇，思无邪，中国诗歌的源头。", ((BODIES.get("classic-shijing", "") + EXTRA.get("classic-shijing", "") + EXTRA2.get("classic-shijing", "")) or _OLD.get("classic-shijing", "")), [{'lib': '诗经', 'id': 'shijing-01'}], {'type': 'character', 'params': {'char': '诗', 'seal': False}}, ['诗经', '诗词', '经典'])
E('wenzi-xiangxing', "象形与汉字", "汉字·文学", "字源流变", "书画同源，一字一世界。", ((BODIES.get("wenzi-xiangxing", "") + EXTRA.get("wenzi-xiangxing", "") + EXTRA2.get("wenzi-xiangxing", "")) or _OLD.get("wenzi-xiangxing", "")), [{'lib': '说文解字', 'id': 'sw-1'}], {'type': 'character', 'params': {'char': '字', 'seal': False}}, ['汉字', '字源', '历史'])
E('wenzi-liushu', "六书", "汉字·文学", "字源流变", "象形指事会意形声，汉字的六把钥匙。", ((BODIES.get("wenzi-liushu", "") + EXTRA.get("wenzi-liushu", "") + EXTRA2.get("wenzi-liushu", "")) or _OLD.get("wenzi-liushu", "")), [{'lib': '说文解字', 'id': 'sw-1'}], {'type': 'character', 'params': {'char': '书', 'seal': False}}, ['汉字', '字源', '历史'])
E('mengxue-qianziwen', "《千字文》", "汉字·文学", "蒙学", "千字不重，四字成韵，童蒙第一书。", ((BODIES.get("mengxue-qianziwen", "") + EXTRA.get("mengxue-qianziwen", "") + EXTRA2.get("mengxue-qianziwen", "")) or _OLD.get("mengxue-qianziwen", "")), [{'lib': '千字文', 'id': 'qz-1'}], {'type': 'character', 'params': {'char': '千', 'seal': False}}, ['千字文', '蒙学', '历史'])
E('mengxue-sanzijing', "《三字经》", "汉字·文学", "蒙学", "三字一句，童蒙须知，最普及的国学启蒙。", ((BODIES.get("mengxue-sanzijing", "") + EXTRA.get("mengxue-sanzijing", "") + EXTRA2.get("mengxue-sanzijing", "")) or _OLD.get("mengxue-sanzijing", "")), [{'lib': '三字经', 'id': 'sze-1'}], {'type': 'character', 'params': {'char': '三', 'seal': False}}, ['三字经', '蒙学', '历史'])
E('wenxue-tangshi', "唐诗", "汉字·文学", "诗词文赋", "一座不可逾越的诗歌巅峰。", ((BODIES.get("wenxue-tangshi", "") + EXTRA.get("wenxue-tangshi", "") + EXTRA2.get("wenxue-tangshi", "")) or _OLD.get("wenxue-tangshi", "")), [{'lib': '文心雕龙', 'id': 'wxd-2'}], {'type': 'character', 'params': {'char': '诗', 'seal': False}}, ['唐诗', '诗词', '历史'])
E('wenxue-songci', "宋词", "汉字·文学", "诗词文赋", "长短句里的婉约与豪放。", ((BODIES.get("wenxue-songci", "") + EXTRA.get("wenxue-songci", "") + EXTRA2.get("wenxue-songci", "")) or _OLD.get("wenxue-songci", "")), [{'lib': '诗经', 'id': 'shijing-qin'}], {'type': 'character', 'params': {'char': '词', 'seal': False}}, ['宋词', '诗词', '历史'])
E('wenxue-chuci', "楚辞", "汉字·文学", "诗词文赋", "一份来自荆楚的浪漫与哀愁。", ((BODIES.get("wenxue-chuci", "") + EXTRA.get("wenxue-chuci", "") + EXTRA2.get("wenxue-chuci", "")) or _OLD.get("wenxue-chuci", "")), [{'lib': '楚辞', 'id': 'chuci-01'}], {'type': 'character', 'params': {'char': '辞', 'seal': False}}, ['楚辞', '诗词', '历史'])
E('wenxue-yueyanglou', "《岳阳楼记》", "汉字·文学", "古文名篇", "不以物喜，不以己悲，士人的千古襟怀。", ((BODIES.get("wenxue-yueyanglou", "") + EXTRA.get("wenxue-yueyanglou", "") + EXTRA2.get("wenxue-yueyanglou", "")) or _OLD.get("wenxue-yueyanglou", "")), [{'lib': '论语', 'id': 'lunyu-6'}], {'type': 'character', 'params': {'char': '记', 'seal': False}}, ['古文', '历史', '闯关'])
E('wenxue-chengyu', "成语源流", "汉字·文学", "古文名篇", "四字之间，藏着一部文化简史。", ((BODIES.get("wenxue-chengyu", "") + EXTRA.get("wenxue-chengyu", "") + EXTRA2.get("wenxue-chengyu", "")) or _OLD.get("wenxue-chengyu", "")), [{'lib': '论语', 'id': 'lunyu-12'}], {'type': 'character', 'params': {'char': '成语', 'seal': False}}, ['成语', '历史', '闯关'])
E('wenxue-shiji', "《史记》", "汉字·文学", "古文名篇", "史家之绝唱，无韵之离骚。", ((BODIES.get("wenxue-shiji", "") + EXTRA.get("wenxue-shiji", "") + EXTRA2.get("wenxue-shiji", "")) or _OLD.get("wenxue-shiji", "")), [{'lib': '史记', 'id': 'shiji-1'}], {'type': 'character', 'params': {'char': '史', 'seal': False}}, ['史记', '历史', '闯关'])
E('wenwen-wenxindiaolong', "《文心雕龙》", "汉字·文学", "古文名篇", "体大思精，中国第一部文章学巨典。", ((BODIES.get("wenwen-wenxindiaolong", "") + EXTRA.get("wenwen-wenxindiaolong", "") + EXTRA2.get("wenwen-wenxindiaolong", "")) or _OLD.get("wenwen-wenxindiaolong", "")), [{'lib': '文心雕龙', 'id': 'wxd-1'}], {'type': 'character', 'params': {'char': '龙', 'seal': False}}, ['文论', '历史', '闯关'])
E('wenxue-yuanqu', "元曲", "汉字·文学", "诗词文赋", "市井里的吟唱，俚俗中的锋芒。", ((BODIES.get("wenxue-yuanqu", "") + EXTRA.get("wenxue-yuanqu", "") + EXTRA2.get("wenxue-yuanqu", "")) or _OLD.get("wenxue-yuanqu", "")), [{'lib': '诗经', 'id': 'shijing-caoxu'}], {'type': 'character', 'params': {'char': '曲', 'seal': False}}, ['元曲', '诗词', '历史'])
E('wenzi-yanbian', "汉字演变", "汉字·文学", "字源流变", "甲金篆隶草楷行，一字千年形变神连。", ((BODIES.get("wenzi-yanbian", "") + EXTRA.get("wenzi-yanbian", "") + EXTRA2.get("wenzi-yanbian", "")) or _OLD.get("wenzi-yanbian", "")), [{'lib': '说文解字', 'id': 'sw-1'}], {'type': 'character', 'params': {'char': '甲', 'seal': False}}, ['汉字', '字源', '历史'])
E('jieqi-chunfen', "春分", "节俗·时令", "二十四节气", "昼夜均分，寒暑相平，仲春之中。", ((BODIES.get("jieqi-chunfen", "") + EXTRA.get("jieqi-chunfen", "") + EXTRA2.get("jieqi-chunfen", "")) or _OLD.get("jieqi-chunfen", "")), [{'lib': '千字文', 'id': 'qz-2'}], {'type': 'solar-term', 'params': {'term': '春分', 'icon': '🌓', 'season': 'spring'}}, ['节气', '仲春', '物候', '民俗', '养生'])
E('jieqi-qingming', "清明", "节俗·时令", "传统节日", "气清景明，慎终追远，踏青插柳。", ((BODIES.get("jieqi-qingming", "") + EXTRA.get("jieqi-qingming", "") + EXTRA2.get("jieqi-qingming", "")) or _OLD.get("jieqi-qingming", "")), [{'lib': '论语', 'id': 'lunyu-20'}], {'type': 'solar-term', 'params': {'term': '清明', 'icon': '🌿', 'season': 'spring'}}, ['节日', '祭祀', '踏青', '民俗', '诗词', '历史'])
E('jieri-duanwu', "端午", "节俗·时令", "传统节日", "龙舟竞渡，角黍寄情，追念屈原。", ((BODIES.get("jieri-duanwu", "") + EXTRA.get("jieri-duanwu", "") + EXTRA2.get("jieri-duanwu", "")) or _OLD.get("jieri-duanwu", "")), [{'lib': '楚辞', 'id': 'chuci-02'}], {'type': 'solar-term', 'params': {'term': '端午', 'icon': '🐉', 'season': 'summer'}}, ['端午', '龙舟', '屈原', '民俗', '成语', '诗词'])
E('jieri-zhongqiu', "中秋", "节俗·时令", "传统节日", "月圆人圆，赏月尝饼，寄远思乡。", ((BODIES.get("jieri-zhongqiu", "") + EXTRA.get("jieri-zhongqiu", "") + EXTRA2.get("jieri-zhongqiu", "")) or _OLD.get("jieri-zhongqiu", "")), [{'lib': '楚辞', 'id': 'chuci-03'}], {'type': 'solar-term', 'params': {'term': '中秋', 'icon': '🌕', 'season': 'autumn'}}, ['中秋', '团圆', '赏月', '诗词', '民俗'])
E('jieri-chunjie', "春节", "节俗·时令", "传统节日", "岁首更始，守岁纳福，万象更新。", ((BODIES.get("jieri-chunjie", "") + EXTRA.get("jieri-chunjie", "") + EXTRA2.get("jieri-chunjie", "")) or _OLD.get("jieri-chunjie", "")), [{'lib': '千字文', 'id': 'qz-1'}], {'type': 'solar-term', 'params': {'term': '春节', 'icon': '🧧', 'season': 'winter'}}, ['春节', '守岁', '民俗', '历史'])
E('ershisi-jieqi', "二十四节气", "节俗·时令", "二十四节气", "仰观天象，俯察物候，时间的诗意刻度。", ((BODIES.get("ershisi-jieqi", "") + EXTRA.get("ershisi-jieqi", "") + EXTRA2.get("ershisi-jieqi", "")) or _OLD.get("ershisi-jieqi", "")), [{'lib': '千字文', 'id': 'qz-2'}], {'type': 'solar-term', 'params': {'term': '节气', 'icon': '🌾', 'season': 'cycle'}}, ['节气', '物候', '农事', '养生'])
E('jieqi-dongzhi', "冬至", "节俗·时令", "二十四节气", "日短之极，阳气始生，数九的开端。", ((BODIES.get("jieqi-dongzhi", "") + EXTRA.get("jieqi-dongzhi", "") + EXTRA2.get("jieqi-dongzhi", "")) or _OLD.get("jieqi-dongzhi", "")), [{'lib': '千字文', 'id': 'qz-2'}], {'type': 'solar-term', 'params': {'term': '冬至', 'icon': '❄️', 'season': 'winter'}}, ['节气', '数九', '民俗', '养生'])
E('jieri-qixi', "七夕", "节俗·时令", "传统节日", "星桥鹊驾，乞巧传情，中国人的情人节。", ((BODIES.get("jieri-qixi", "") + EXTRA.get("jieri-qixi", "") + EXTRA2.get("jieri-qixi", "")) or _OLD.get("jieri-qixi", "")), [{'lib': '诗经', 'id': 'shijing-qin'}], {'type': 'solar-term', 'params': {'term': '七夕', 'icon': '💕', 'season': 'summer'}}, ['七夕', '乞巧', '民俗', '诗词'])
E('jieri-chongyang', "重阳", "节俗·时令", "传统节日", "登高辞青，茱萸菊花，敬老的秋日。", ((BODIES.get("jieri-chongyang", "") + EXTRA.get("jieri-chongyang", "") + EXTRA2.get("jieri-chongyang", "")) or _OLD.get("jieri-chongyang", "")), [{'lib': '楚辞', 'id': 'chuci-03'}], {'type': 'solar-term', 'params': {'term': '重阳', 'icon': '🍂', 'season': 'autumn'}}, ['重阳', '登高', '敬老', '诗词', '民俗'])
E('jieri-laba', "腊八", "节俗·时令", "民俗风物", "腊尽春回，一碗粥里的年味序曲。", ((BODIES.get("jieri-laba", "") + EXTRA.get("jieri-laba", "") + EXTRA2.get("jieri-laba", "")) or _OLD.get("jieri-laba", "")), [{'lib': '朱子家训', 'id': 'zz-2'}], {'type': 'solar-term', 'params': {'term': '腊八', 'icon': '🥣', 'season': 'winter'}}, ['腊八', '年味', '民俗', '饮食', '养生'])
E('jieri-zhongyuan', "中元节", "节俗·时令", "传统节日", "慎终追远，七月半的孝亲与慈悲。", ((BODIES.get("jieri-zhongyuan", "") + EXTRA.get("jieri-zhongyuan", "") + EXTRA2.get("jieri-zhongyuan", "")) or _OLD.get("jieri-zhongyuan", "")), [{'lib': '礼记', 'id': 'liji-3'}], {'type': 'solar-term', 'params': {'term': '中元', 'icon': '🪔', 'season': 'autumn'}}, ['中元', '祭祖', '民俗', '孝亲'])
E('jieri-longtaitou', "龙抬头", "节俗·时令", "二十四节气", "二月二，龙抬头，春耕与剃头的欢喜。", ((BODIES.get("jieri-longtaitou", "") + EXTRA.get("jieri-longtaitou", "") + EXTRA2.get("jieri-longtaitou", "")) or _OLD.get("jieri-longtaitou", "")), [{'lib': '千字文', 'id': 'qz-2'}], {'type': 'solar-term', 'params': {'term': '龙抬头', 'icon': '🐲', 'season': 'spring'}}, ['龙抬头', '春耕', '民俗', '节气'])
E('yishu-shufa', "书法", "艺术·工艺", "书法", "笔墨的舞蹈，中国人最日常也最极致的艺术。", ((BODIES.get("yishu-shufa", "") + EXTRA.get("yishu-shufa", "") + EXTRA2.get("yishu-shufa", "")) or _OLD.get("yishu-shufa", "")), [{'lib': '说文解字', 'id': 'sw-1'}], {'type': 'character', 'params': {'char': '书', 'seal': False}}, ['书法', '历史', '闯关'])
E('yishu-shuimo', "国画", "艺术·工艺", "国画", "水墨丹青，留白处皆是天地。", ((BODIES.get("yishu-shuimo", "") + EXTRA.get("yishu-shuimo", "") + EXTRA2.get("yishu-shuimo", "")) or _OLD.get("yishu-shuimo", "")), [{'lib': '文心雕龙', 'id': 'wxd-2'}], {'type': 'character', 'params': {'char': '画', 'seal': False}}, ['国画', '历史', '闯关'])
E('yishu-jingju', "京剧", "艺术·工艺", "戏曲", "唱念做打，脸谱乾坤，国粹的百味。", ((BODIES.get("yishu-jingju", "") + EXTRA.get("yishu-jingju", "") + EXTRA2.get("yishu-jingju", "")) or _OLD.get("yishu-jingju", "")), [{'lib': '诗经', 'id': 'shijing-01'}], {'type': 'object', 'params': {'kind': 'mask', 'label': '脸谱'}}, ['京剧', '戏曲', '历史', '闯关'])
E('yishu-qinghua', "青花瓷", "艺术·工艺", "器物建筑", "白地蓝花，一抹东方的幽蓝。", ((BODIES.get("yishu-qinghua", "") + EXTRA.get("yishu-qinghua", "") + EXTRA2.get("yishu-qinghua", "")) or _OLD.get("yishu-qinghua", "")), [{'lib': '易经', 'id': 'yj-4'}], {'type': 'object', 'params': {'kind': 'vase', 'label': '青花'}}, ['青花瓷', '历史', '闯关'])
E('yishu-guqin', "古琴", "艺术·工艺", "器物建筑", "七弦泠泠，士人精神的知音。", ((BODIES.get("yishu-guqin", "") + EXTRA.get("yishu-guqin", "") + EXTRA2.get("yishu-guqin", "")) or _OLD.get("yishu-guqin", "")), [{'lib': '诗经', 'id': 'shijing-qin'}], {'type': 'character', 'params': {'char': '琴', 'seal': False}}, ['古琴', '历史', '闯关'])
E('yishu-yunwen', "纹样寓意", "艺术·工艺", "纹样寓意", "图必有意，意必吉祥。", ((BODIES.get("yishu-yunwen", "") + EXTRA.get("yishu-yunwen", "") + EXTRA2.get("yishu-yunwen", "")) or _OLD.get("yishu-yunwen", "")), [{'lib': '易经', 'id': 'yj-4'}], {'type': 'object', 'params': {'kind': 'cloud', 'label': '云纹'}}, ['纹样', '历史', '闯关'])
E('yishu-yuanlin', "园林", "艺术·工艺", "器物建筑", "虽由人作，宛自天开。", ((BODIES.get("yishu-yuanlin", "") + EXTRA.get("yishu-yuanlin", "") + EXTRA2.get("yishu-yuanlin", "")) or _OLD.get("yishu-yuanlin", "")), [{'lib': '庄子', 'id': 'zhuangzi-2'}], {'type': 'object', 'params': {'kind': 'garden', 'label': '园林'}}, ['园林', '历史', '闯关'])
E('yishu-sunmao', "榫卯", "艺术·工艺", "器物建筑", "不施一钉，木与木的咬合。", ((BODIES.get("yishu-sunmao", "") + EXTRA.get("yishu-sunmao", "") + EXTRA2.get("yishu-sunmao", "")) or _OLD.get("yishu-sunmao", "")), [{'lib': '周礼', 'id': 'zl-1'}], {'type': 'character', 'params': {'char': '卯', 'seal': False}}, ['榫卯', '历史', '闯关'])
E('yishu-zhuanke', "篆刻", "艺术·工艺", "书法", "方寸之间，刀笔的金石气。", ((BODIES.get("yishu-zhuanke", "") + EXTRA.get("yishu-zhuanke", "") + EXTRA2.get("yishu-zhuanke", "")) or _OLD.get("yishu-zhuanke", "")), [{'lib': '说文解字', 'id': 'sw-1'}], {'type': 'character', 'params': {'char': '印', 'seal': False}}, ['篆刻', '历史', '闯关'])
E('yishu-cixiu', "刺绣", "艺术·工艺", "纹样寓意", "针线为笔，丝帛为纸的丹青。", ((BODIES.get("yishu-cixiu", "") + EXTRA.get("yishu-cixiu", "") + EXTRA2.get("yishu-cixiu", "")) or _OLD.get("yishu-cixiu", "")), [{'lib': '楚辞', 'id': 'chuci-03'}], {'type': 'character', 'params': {'char': '绣', 'seal': False}}, ['刺绣', '历史', '闯关'])
E('yishu-yuqi', "玉器", "艺术·工艺", "器物建筑", "君子比德于玉，温润而坚刚。", ((BODIES.get("yishu-yuqi", "") + EXTRA.get("yishu-yuqi", "") + EXTRA2.get("yishu-yuqi", "")) or _OLD.get("yishu-yuqi", "")), [{'lib': '礼记', 'id': 'liji-4'}], {'type': 'character', 'params': {'char': '玉', 'seal': False}}, ['玉器', '历史', '闯关'])
E('yishu-qiqi', "漆器", "艺术·工艺", "器物建筑", "千文万华，髹饰之工。", ((BODIES.get("yishu-qiqi", "") + EXTRA.get("yishu-qiqi", "") + EXTRA2.get("yishu-qiqi", "")) or _OLD.get("yishu-qiqi", "")), [{'lib': '诗经', 'id': 'shijing-07'}], {'type': 'character', 'params': {'char': '漆', 'seal': False}}, ['漆器', '历史', '闯关'])
E('yishu-bingmayong', "兵马俑", "艺术·工艺", "器物建筑", "泥土塑出的帝国军团。", ((BODIES.get("yishu-bingmayong", "") + EXTRA.get("yishu-bingmayong", "") + EXTRA2.get("yishu-bingmayong", "")) or _OLD.get("yishu-bingmayong", "")), [{'lib': '周礼', 'id': 'zl-1'}], {'type': 'character', 'params': {'char': '俑', 'seal': False}}, ['兵马俑', '历史', '闯关'])
E('liyi-guanli', "冠礼与笄礼", "衣食·礼制", "礼节", "男子二十而冠，女子十五而笄，成年的加冕。", ((BODIES.get("liyi-guanli", "") + EXTRA.get("liyi-guanli", "") + EXTRA2.get("liyi-guanli", "")) or _OLD.get("liyi-guanli", "")), [{'lib': '礼记', 'id': 'liji-1'}], {'type': 'character', 'params': {'char': '冠', 'seal': False}}, ['冠礼', '礼节', '历史'])
E('liyi-hunli', "婚姻六礼", "衣食·礼制", "礼节", "纳采问名，执子之手，中国人的嫁娶之仪。", ((BODIES.get("liyi-hunli", "") + EXTRA.get("liyi-hunli", "") + EXTRA2.get("liyi-hunli", "")) or _OLD.get("liyi-hunli", "")), [{'lib': '诗经', 'id': 'shijing-qin'}], {'type': 'character', 'params': {'char': '婚', 'seal': False}}, ['婚礼', '礼节', '历史'])
E('liyi-zuoci', "座次与揖让", "衣食·礼制", "礼节", "席不正不坐，中国人的空间秩序。", ((BODIES.get("liyi-zuoci", "") + EXTRA.get("liyi-zuoci", "") + EXTRA2.get("liyi-zuoci", "")) or _OLD.get("liyi-zuoci", "")), [{'lib': '礼记', 'id': 'liji-2'}], {'type': 'character', 'params': {'char': '礼', 'seal': False}}, ['座次', '礼节', '历史'])
E('liyi-bihui', "相见与聘礼", "衣食·礼制", "礼节", "币帛为贽，礼尚往来。", ((BODIES.get("liyi-bihui", "") + EXTRA.get("liyi-bihui", "") + EXTRA2.get("liyi-bihui", "")) or _OLD.get("liyi-bihui", "")), [{'lib': '礼记', 'id': 'liji-2'}], {'type': 'character', 'params': {'char': '币', 'seal': False}}, ['礼节', '历史', '闯关'])
E('jiaxun-zhuzi', "《朱子家训》", "衣食·礼制", "家训门风", "一粥一饭，当思来处不易。", ((BODIES.get("jiaxun-zhuzi", "") + EXTRA.get("jiaxun-zhuzi", "") + EXTRA2.get("jiaxun-zhuzi", "")) or _OLD.get("jiaxun-zhuzi", "")), [{'lib': '朱子家训', 'id': 'zz-2'}], {'type': 'character', 'params': {'char': '训', 'seal': False}}, ['家训', '历史', '闯关'])
E('mengxue-dizigui', "《弟子规》", "衣食·礼制", "家训门风", "入则孝，出则悌，童蒙的力行规范。", ((BODIES.get("mengxue-dizigui", "") + EXTRA.get("mengxue-dizigui", "") + EXTRA2.get("mengxue-dizigui", "")) or _OLD.get("mengxue-dizigui", "")), [{'lib': '弟子规', 'id': 'dzg-1'}], {'type': 'character', 'params': {'char': '规', 'seal': False}}, ['弟子规', '家训', '历史'])
E('yinshi-cha', "茶道", "衣食·礼制", "饮食", "一盏清茶，喝的是中国人慢下来的哲学。", ((BODIES.get("yinshi-cha", "") + EXTRA.get("yinshi-cha", "") + EXTRA2.get("yinshi-cha", "")) or _OLD.get("yinshi-cha", "")), [{'lib': '六祖坛经', 'id': 'zc-1'}], {'type': 'object', 'params': {'kind': 'tea', 'label': '茶'}}, ['茶', '饮食', '养生'])
E('yinshi-caixi', "八大菜系", "衣食·礼制", "饮食", "一方水土，一方滋味。", ((BODIES.get("yinshi-caixi", "") + EXTRA.get("yinshi-caixi", "") + EXTRA2.get("yinshi-caixi", "")) or _OLD.get("yinshi-caixi", "")), [{'lib': '朱子家训', 'id': 'zz-2'}], {'type': 'character', 'params': {'char': '食', 'seal': False}}, ['饮食', '菜系', '养生'])
E('yinshi-kuaizi', "筷子", "衣食·礼制", "饮食", "一双七寸六分，夹起的是文明。", ((BODIES.get("yinshi-kuaizi", "") + EXTRA.get("yinshi-kuaizi", "") + EXTRA2.get("yinshi-kuaizi", "")) or _OLD.get("yinshi-kuaizi", "")), [{'lib': '朱子家训', 'id': 'zz-2'}], {'type': 'character', 'params': {'char': '箸', 'seal': False}}, ['筷子', '饮食', '养生'])
E('fushi-hanfu', "汉服", "衣食·礼制", "服饰", "华夏衣冠，不止是衣裳。", ((BODIES.get("fushi-hanfu", "") + EXTRA.get("fushi-hanfu", "") + EXTRA2.get("fushi-hanfu", "")) or _OLD.get("fushi-hanfu", "")), [{'lib': '礼记', 'id': 'liji-2'}], {'type': 'object', 'params': {'kind': 'robe', 'label': '深衣'}}, ['汉服', '服饰', '历史'])
E('liyi-sangji', "丧祭之礼", "衣食·礼制", "礼节", "慎终追远，民德归厚。", ((BODIES.get("liyi-sangji", "") + EXTRA.get("liyi-sangji", "") + EXTRA2.get("liyi-sangji", "")) or _OLD.get("liyi-sangji", "")), [{'lib': '礼记', 'id': 'liji-1'}], {'type': 'character', 'params': {'char': '祭', 'seal': False}}, ['丧祭', '礼节', '历史'])
E('fushi-dengji', "服饰等级", "衣食·礼制", "服饰", "衣冠有等，章纹辨尊卑。", ((BODIES.get("fushi-dengji", "") + EXTRA.get("fushi-dengji", "") + EXTRA2.get("fushi-dengji", "")) or _OLD.get("fushi-dengji", "")), [{'lib': '周礼', 'id': 'zl-1'}], {'type': 'character', 'params': {'char': '衣', 'seal': False}}, ['服饰', '等级', '历史'])
E('liyi-jiali', "朱子家礼", "衣食·礼制", "家训门风", "冠婚丧祭，居家日用之仪。", ((BODIES.get("liyi-jiali", "") + EXTRA.get("liyi-jiali", "") + EXTRA2.get("liyi-jiali", "")) or _OLD.get("liyi-jiali", "")), [{'lib': '朱子家训', 'id': 'zz-1'}], {'type': 'character', 'params': {'char': '家', 'seal': False}}, ['家礼', '家训', '历史', '闯关'])
E('mingjia', "名家", "思想哲学", "名家", "专攻名实之辩的先秦学派，中国逻辑与语言哲学之先声。", ((BODIES.get("mingjia", "") + EXTRA.get("mingjia", "") + EXTRA2.get("mingjia", "")) or _OLD.get("mingjia", "")), None, {'type': 'character', 'params': {'char': '名', 'seal': False}}, ['名家', '名辩', '逻辑'])
E('jingxue', "经学", "思想哲学", "儒家", "训解阐发儒家经典的学问，两千年士人的共同底色。", ((BODIES.get("jingxue", "") + EXTRA.get("jingxue", "") + EXTRA2.get("jingxue", "")) or _OLD.get("jingxue", "")), [{'lib': '汉书', 'id': 'hanshu-1'}], {'type': 'character', 'params': {'char': '经', 'seal': False}}, ['经学', '儒家', '历史'])
E('shixue', "实学", "思想哲学", "儒家", "明清勃兴的经世致用思潮，反对空谈性理。", ((BODIES.get("shixue", "") + EXTRA.get("shixue", "") + EXTRA2.get("shixue", "")) or _OLD.get("shixue", "")), [{'lib': '传习录', 'id': 'czl-1'}], {'type': 'character', 'params': {'char': '实', 'seal': False}}, ['实学', '明清', '经世'])
E('wenzi-shuowen', "《说文解字》", "汉字·文学", "字源流变", "中国第一部系统分析字形、说解字义的字典。", ((BODIES.get("wenzi-shuowen", "") + EXTRA.get("wenzi-shuowen", "") + EXTRA2.get("wenzi-shuowen", "")) or _OLD.get("wenzi-shuowen", "")), [{'lib': '说文解字', 'id': 'sw-1'}], {'type': 'character', 'params': {'char': '说', 'seal': False}}, ['说文', '字源', '小学'])
E('hanfu-yuefu', "汉赋与乐府", "汉字·文学", "诗词文赋", "汉代文学的两副面相：庙堂之赋与民间之乐。", ((BODIES.get("hanfu-yuefu", "") + EXTRA.get("hanfu-yuefu", "") + EXTRA2.get("hanfu-yuefu", "")) or _OLD.get("hanfu-yuefu", "")), [{'lib': '楚辞', 'id': 'chuci-01'}], {'type': 'character', 'params': {'char': '赋', 'seal': False}}, ['汉赋', '乐府', '诗词'])
E('biji', "笔记小说", "汉字·文学", "古文名篇", "古人随笔记闻的杂著，最见性情与世相。", ((BODIES.get("biji", "") + EXTRA.get("biji", "") + EXTRA2.get("biji", "")) or _OLD.get("biji", "")), [{'lib': '文心雕龙', 'id': 'wxd-1'}], {'type': 'character', 'params': {'char': '笔', 'seal': False}}, ['笔记', '小说', '文学'])
E('duilian', "楹联", "汉字·文学", "诗词文赋", "由骈文律诗对仗发展而来的对称文学。", ((BODIES.get("duilian", "") + EXTRA.get("duilian", "") + EXTRA2.get("duilian", "")) or _OLD.get("duilian", "")), None, {'type': 'character', 'params': {'char': '联', 'seal': False}}, ['对联', '楹联', '文学'])
E('jieri-shangsi', "上巳节", "节俗·时令", "传统节日", "农历三月初三的水边祓禊与春游之日。", ((BODIES.get("jieri-shangsi", "") + EXTRA.get("jieri-shangsi", "") + EXTRA2.get("jieri-shangsi", "")) or _OLD.get("jieri-shangsi", "")), None, {'type': 'solar-term', 'params': {'term': '上巳', 'icon': '🌸', 'season': 'spring'}}, ['上巳', '节日', '民俗'])
E('jieri-sheri', "社日", "节俗·时令", "民俗风物", "祭祀土地神的春祈秋报之节。", ((BODIES.get("jieri-sheri", "") + EXTRA.get("jieri-sheri", "") + EXTRA2.get("jieri-sheri", "")) or _OLD.get("jieri-sheri", "")), [{'lib': '礼记', 'id': 'liji-1'}], {'type': 'character', 'params': {'char': '社', 'seal': False}}, ['社日', '农耕', '民俗'])
E('jieqi-lichun', "立春", "节俗·时令", "二十四节气", "二十四节气之首，一岁农事之起点。", ((BODIES.get("jieqi-lichun", "") + EXTRA.get("jieqi-lichun", "") + EXTRA2.get("jieqi-lichun", "")) or _OLD.get("jieqi-lichun", "")), None, {'type': 'solar-term', 'params': {'term': '立春', 'icon': '🌱', 'season': 'spring'}}, ['立春', '节气', '民俗'])
E('lishi-xiashangzhou', "夏商周三代", "历史脉络", "朝代变迁", "中国王朝时代的开端，礼乐文明之奠基。", ((BODIES.get("lishi-xiashangzhou", "") + EXTRA.get("lishi-xiashangzhou", "") + EXTRA2.get("lishi-xiashangzhou", "")) or _OLD.get("lishi-xiashangzhou", "")), [{'lib': '禹贡', 'id': 'yg-1'}], {'type': 'character', 'params': {'char': '夏', 'seal': False}}, ['三代', '青铜', '历史'])
E('lishi-nanbeichao', "南北朝", "历史脉络", "朝代变迁", "三百年的南北分裂与民族大融合。", ((BODIES.get("lishi-nanbeichao", "") + EXTRA.get("lishi-nanbeichao", "") + EXTRA2.get("lishi-nanbeichao", "")) or _OLD.get("lishi-nanbeichao", "")), [{'lib': '资治通鉴', 'id': 'zztj-1'}], {'type': 'character', 'params': {'char': '南', 'seal': False}}, ['南北朝', '分裂', '历史'])
E('lishi-wudai', "五代十国", "历史脉络", "朝代变迁", "唐亡后五十余年的中原易代与藩镇之祸。", ((BODIES.get("lishi-wudai", "") + EXTRA.get("lishi-wudai", "") + EXTRA2.get("lishi-wudai", "")) or _OLD.get("lishi-wudai", "")), None, {'type': 'character', 'params': {'char': '五', 'seal': False}}, ['五代', '分裂', '历史'])
E('lishi-liaojinxixia', "辽金西夏", "历史脉络", "民族", "两宋并立的北方三朝，多政权共存之局。", ((BODIES.get("lishi-liaojinxixia", "") + EXTRA.get("lishi-liaojinxixia", "") + EXTRA2.get("lishi-liaojinxixia", "")) or _OLD.get("lishi-liaojinxixia", "")), None, {'type': 'character', 'params': {'char': '辽', 'seal': False}}, ['辽金', '民族', '历史'])
E('yishu-dunhuang', "敦煌石窟", "艺术·工艺", "器物建筑", "丝绸之路上的佛教艺术宝库。", ((BODIES.get("yishu-dunhuang", "") + EXTRA.get("yishu-dunhuang", "") + EXTRA2.get("yishu-dunhuang", "")) or _OLD.get("yishu-dunhuang", "")), None, {'type': 'character', 'params': {'char': '窟', 'seal': False}}, ['敦煌', '石窟', '佛教'])
E('yishu-qingtong', "青铜器", "艺术·工艺", "器物建筑", "商周礼器与兵器，权力与礼制的物质化身。", ((BODIES.get("yishu-qingtong", "") + EXTRA.get("yishu-qingtong", "") + EXTRA2.get("yishu-qingtong", "")) or _OLD.get("yishu-qingtong", "")), [{'lib': '周礼', 'id': 'zl-1'}], {'type': 'character', 'params': {'char': '鼎', 'seal': False}}, ['青铜', '礼器', '工艺'])
E('yishu-tangsancai', "唐三彩", "艺术·工艺", "器物建筑", "唐代低温釉陶，盛唐气象的釉上投影。", ((BODIES.get("yishu-tangsancai", "") + EXTRA.get("yishu-tangsancai", "") + EXTRA2.get("yishu-tangsancai", "")) or _OLD.get("yishu-tangsancai", "")), None, {'type': 'character', 'params': {'char': '彩', 'seal': False}}, ['唐三彩', '陶艺', '工艺'])
E('yishu-wenfang', "文房四宝", "艺术·工艺", "器物建筑", "笔墨纸砚，文人书写的器物与审美。", ((BODIES.get("yishu-wenfang", "") + EXTRA.get("yishu-wenfang", "") + EXTRA2.get("yishu-wenfang", "")) or _OLD.get("yishu-wenfang", "")), [{'lib': '文心雕龙', 'id': 'wxd-1'}], {'type': 'character', 'params': {'char': '墨', 'seal': False}}, ['文房', '笔墨', '工艺'])
E('minju-sihayuan', "中华民居", "衣食·礼制", "服饰", "因地理气候与家族制度而异的居住智慧。", ((BODIES.get("minju-sihayuan", "") + EXTRA.get("minju-sihayuan", "") + EXTRA2.get("minju-sihayuan", "")) or _OLD.get("minju-sihayuan", "")), [{'lib': '周礼', 'id': 'zl-1'}], {'type': 'character', 'params': {'char': '居', 'seal': False}}, ['民居', '建筑', '礼制'])
E('liyi-yanxiang', "宴飨之礼", "衣食·礼制", "礼节", "以饮食通伦理的古礼。", ((BODIES.get("liyi-yanxiang", "") + EXTRA.get("liyi-yanxiang", "") + EXTRA2.get("liyi-yanxiang", "")) or _OLD.get("liyi-yanxiang", "")), [{'lib': '礼记', 'id': 'liji-1'}], {'type': 'character', 'params': {'char': '宴', 'seal': False}}, ['宴飨', '礼节', '饮食'])
E('yi-huangdi', "《黄帝内经》", "医药·养生", "中医源流", "中国最早的医学典籍，中医理论的骨架。", ((BODIES.get("yi-huangdi", "") + EXTRA.get("yi-huangdi", "") + EXTRA2.get("yi-huangdi", "")) or _OLD.get("yi-huangdi", "")), [{'lib': '黄帝内经', 'id': 'nh-1'}], {'type': 'character', 'params': {'char': '医', 'seal': False}}, ['黄帝内经', '中医', '经典'])
E('yi-jichu', "中医基础", "医药·养生", "中医源流", "阴阳五行、藏象气血：中医看人的底层逻辑。", ((BODIES.get("yi-jichu", "") + EXTRA.get("yi-jichu", "") + EXTRA2.get("yi-jichu", "")) or _OLD.get("yi-jichu", "")), [{'lib': '黄帝内经', 'id': 'nh-2'}], {'type': 'character', 'params': {'char': '阴', 'seal': False}}, ['阴阳', '藏象', '中医'])
E('yi-shanghan', "伤寒论与张仲景", "医药·养生", "中医源流", "辨证论治的范式，方书之祖。", ((BODIES.get("yi-shanghan", "") + EXTRA.get("yi-shanghan", "") + EXTRA2.get("yi-shanghan", "")) or _OLD.get("yi-shanghan", "")), [{'lib': '伤寒论', 'id': 'shl-1'}], {'type': 'character', 'params': {'char': '寒', 'seal': False}}, ['伤寒论', '张仲景', '医典'])
E('yi-bencao', "本草纲目与李时珍", "医药·养生", "本草方药", "集大成的药物学巨著，古代百科全书。", ((BODIES.get("yi-bencao", "") + EXTRA.get("yi-bencao", "") + EXTRA2.get("yi-bencao", "")) or _OLD.get("yi-bencao", "")), [{'lib': '本草纲目', 'id': 'bc-1'}], {'type': 'character', 'params': {'char': '草', 'seal': False}}, ['本草纲目', '李时珍', '本草'])
E('yi-zhenjiu', "针灸", "医药·养生", "针灸导引", "针与灸的外治法，中医最具标志性的技艺。", ((BODIES.get("yi-zhenjiu", "") + EXTRA.get("yi-zhenjiu", "") + EXTRA2.get("yi-zhenjiu", "")) or _OLD.get("yi-zhenjiu", "")), None, {'type': 'character', 'params': {'char': '针', 'seal': False}}, ['针灸', '经络', '中医'])
E('yi-jingluo', "经络气血", "医药·养生", "针灸导引", "古人对身体联络系统的关系性建模。", ((BODIES.get("yi-jingluo", "") + EXTRA.get("yi-jingluo", "") + EXTRA2.get("yi-jingluo", "")) or _OLD.get("yi-jingluo", "")), None, {'type': 'character', 'params': {'char': '络', 'seal': False}}, ['经络', '气血', '中医'])
E('yi-qianjin', "千金方与孙思邈", "医药·养生", "中医源流", "集唐以前医方之大成，药王孙思邈。", ((BODIES.get("yi-qianjin", "") + EXTRA.get("yi-qianjin", "") + EXTRA2.get("yi-qianjin", "")) or _OLD.get("yi-qianjin", "")), [{'lib': '千金方', 'id': 'qj-1'}], {'type': 'character', 'params': {'char': '仁', 'seal': False}}, ['千金方', '孙思邈', '医德'])
E('yi-wenbing', "温病学派", "医药·养生", "中医源流", "明清成熟的温热疫邪诊治体系。", ((BODIES.get("yi-wenbing", "") + EXTRA.get("yi-wenbing", "") + EXTRA2.get("yi-wenbing", "")) or _OLD.get("yi-wenbing", "")), None, {'type': 'character', 'params': {'char': '瘟', 'seal': False}}, ['温病', '瘟疫', '中医'])
E('yi-daoyin', "导引·五禽戏·八段锦", "医药·养生", "针灸导引", "导气引体的传统养生术。", ((BODIES.get("yi-daoyin", "") + EXTRA.get("yi-daoyin", "") + EXTRA2.get("yi-daoyin", "")) or _OLD.get("yi-daoyin", "")), None, {'type': 'character', 'params': {'char': '导', 'seal': False}}, ['导引', '养生', '功法'])
E('yi-siyang', "四时养生", "医药·养生", "养生观念", "春生夏长秋收冬藏，顺天应时。", ((BODIES.get("yi-siyang", "") + EXTRA.get("yi-siyang", "") + EXTRA2.get("yi-siyang", "")) or _OLD.get("yi-siyang", "")), [{'lib': '黄帝内经', 'id': 'nh-3'}], {'type': 'character', 'params': {'char': '养', 'seal': False}}, ['养生', '四时', '顺应'])
E('yi-shiliao', "食疗", "医药·养生", "养生观念", "药食同源，以膳食调养身体。", ((BODIES.get("yi-shiliao", "") + EXTRA.get("yi-shiliao", "") + EXTRA2.get("yi-shiliao", "")) or _OLD.get("yi-shiliao", "")), None, {'type': 'character', 'params': {'char': '食', 'seal': False}}, ['食疗', '食养', '养生'])
E('yi-fangyi', "中医防疫", "医药·养生", "养生观念", "正气存内，邪不可干的传统智慧。", ((BODIES.get("yi-fangyi", "") + EXTRA.get("yi-fangyi", "") + EXTRA2.get("yi-fangyi", "")) or _OLD.get("yi-fangyi", "")), None, {'type': 'character', 'params': {'char': '疫', 'seal': False}}, ['防疫', '瘟疫', '中医'])
E('yi-bencao-yaoxing', "本草药性", "医药·养生", "本草方药", "四气五味归经，用药的底层逻辑。", ((BODIES.get("yi-bencao-yaoxing", "") + EXTRA.get("yi-bencao-yaoxing", "") + EXTRA2.get("yi-bencao-yaoxing", "")) or _OLD.get("yi-bencao-yaoxing", "")), [{'lib': '本草纲目', 'id': 'bc-2'}], {'type': 'character', 'params': {'char': '药', 'seal': False}}, ['药性', '本草', '中医'])
E('yi-dayi', "大医精诚", "医药·养生", "中医源流", "孙思邈立下的医德准绳。", ((BODIES.get("yi-dayi", "") + EXTRA.get("yi-dayi", "") + EXTRA2.get("yi-dayi", "")) or _OLD.get("yi-dayi", "")), [{'lib': '千金方', 'id': 'qj-1'}], {'type': 'character', 'params': {'char': '德', 'seal': False}}, ['医德', '大医精诚', '医道'])
E('keji-sida', "四大发明", "科技·发明", "四大发明", "造纸印刷火药指南针，改变世界的中国技术。", ((BODIES.get("keji-sida", "") + EXTRA.get("keji-sida", "") + EXTRA2.get("keji-sida", "")) or _OLD.get("keji-sida", "")), [{'lib': '梦溪笔谈', 'id': 'mxt-1'}], {'type': 'character', 'params': {'char': '器', 'seal': False}}, ['四大发明', '科技', '闯关'])
E('keji-zaozhi', "造纸术", "科技·发明", "四大发明", "蔡伦改进的造纸术，知识传播的基础设施革命。", ((BODIES.get("keji-zaozhi", "") + EXTRA.get("keji-zaozhi", "") + EXTRA2.get("keji-zaozhi", "")) or _OLD.get("keji-zaozhi", "")), None, {'type': 'character', 'params': {'char': '纸', 'seal': False}}, ['造纸', '蔡伦', '发明'])
E('keji-yinshua', "印刷术", "科技·发明", "四大发明", "雕版到活字，毕昇早于古腾堡约四百年。", ((BODIES.get("keji-yinshua", "") + EXTRA.get("keji-yinshua", "") + EXTRA2.get("keji-yinshua", "")) or _OLD.get("keji-yinshua", "")), [{'lib': '梦溪笔谈', 'id': 'mxt-1'}], {'type': 'character', 'params': {'char': '印', 'seal': False}}, ['印刷', '活字', '发明'])
E('keji-huoyao', "火药", "科技·发明", "四大发明", "源于炼丹，改变战争形态的中国发明。", ((BODIES.get("keji-huoyao", "") + EXTRA.get("keji-huoyao", "") + EXTRA2.get("keji-huoyao", "")) or _OLD.get("keji-huoyao", "")), None, {'type': 'character', 'params': {'char': '火', 'seal': False}}, ['火药', '炼丹', '发明'])
E('keji-zhinan', "指南针", "科技·发明", "四大发明", "从司南到航海罗盘，大航海的技术支点。", ((BODIES.get("keji-zhinan", "") + EXTRA.get("keji-zhinan", "") + EXTRA2.get("keji-zhinan", "")) or _OLD.get("keji-zhinan", "")), [{'lib': '梦溪笔谈', 'id': 'mxt-1'}], {'type': 'object', 'params': {'kind': 'compass', 'label': None}}, ['指南针', '司南', '航海'])
E('keji-tianwen', "天文历法", "科技·发明", "天文历法", "观象授时，把星空变成农耕文明的时钟。", ((BODIES.get("keji-tianwen", "") + EXTRA.get("keji-tianwen", "") + EXTRA2.get("keji-tianwen", "")) or _OLD.get("keji-tianwen", "")), [{'lib': '易经', 'id': 'yj-4'}], {'type': 'character', 'params': {'char': '天', 'seal': False}}, ['天文', '历法', '科技'])
E('keji-zhangheng', "张衡与仪器", "科技·发明", "天文历法", "浑天仪与地动仪，古代科学家的范本。", ((BODIES.get("keji-zhangheng", "") + EXTRA.get("keji-zhangheng", "") + EXTRA2.get("keji-zhangheng", "")) or _OLD.get("keji-zhangheng", "")), None, {'type': 'character', 'params': {'char': '仪', 'seal': False}}, ['张衡', '地动仪', '天文'])
E('keji-nongxue', "农学（齐民要术）", "科技·发明", "工农营造", "以农立国的技术体系，顺天量地。", ((BODIES.get("keji-nongxue", "") + EXTRA.get("keji-nongxue", "") + EXTRA2.get("keji-nongxue", "")) or _OLD.get("keji-nongxue", "")), [{'lib': '齐民要术', 'id': 'qm-1'}], {'type': 'character', 'params': {'char': '农', 'seal': False}}, ['农学', '贾思勰', '科技'])
E('keji-shuxue', "数学（祖冲之）", "科技·发明", "天文历法", "问题驱动的中国算法传统。", ((BODIES.get("keji-shuxue", "") + EXTRA.get("keji-shuxue", "") + EXTRA2.get("keji-shuxue", "")) or _OLD.get("keji-shuxue", "")), None, {'type': 'character', 'params': {'char': '数', 'seal': False}}, ['数学', '祖冲之', '科技'])
E('keji-shuili', "水利（都江堰）", "科技·发明", "水利交通", "因势利导的生态水利范本。", ((BODIES.get("keji-shuili", "") + EXTRA.get("keji-shuili", "") + EXTRA2.get("keji-shuili", "")) or _OLD.get("keji-shuili", "")), None, {'type': 'character', 'params': {'char': '水', 'seal': False}}, ['水利', '都江堰', '工程'])
E('keji-yejin', "冶金铸造", "科技·发明", "工农营造", "从青铜范铸到钢铁冶炼的文明筋骨。", ((BODIES.get("keji-yejin", "") + EXTRA.get("keji-yejin", "") + EXTRA2.get("keji-yejin", "")) or _OLD.get("keji-yejin", "")), [{'lib': '天工开物', 'id': 'tg-2'}], {'type': 'character', 'params': {'char': '金', 'seal': False}}, ['冶金', '青铜', '科技'])
E('keji-zaochuan', "造船与航海", "科技·发明", "水利交通", "水密隔舱与罗盘撑起的远洋时代。", ((BODIES.get("keji-zaochuan", "") + EXTRA.get("keji-zaochuan", "") + EXTRA2.get("keji-zaochuan", "")) or _OLD.get("keji-zaochuan", "")), None, {'type': 'character', 'params': {'char': '舟', 'seal': False}}, ['造船', '航海', '科技'])
E('keji-yingzao', "建筑科技（营造法式）", "科技·发明", "工农营造", "以材为模数的官方建筑规范。", ((BODIES.get("keji-yingzao", "") + EXTRA.get("keji-yingzao", "") + EXTRA2.get("keji-yingzao", "")) or _OLD.get("keji-yingzao", "")), [{'lib': '营造法式', 'id': 'yz-1'}], {'type': 'character', 'params': {'char': '营', 'seal': False}}, ['建筑', '营造法式', '科技'])
E('keji-fangzhi', "丝织", "科技·发明", "工农营造", "一根蚕丝牵动的文明交流线。", ((BODIES.get("keji-fangzhi", "") + EXTRA.get("keji-fangzhi", "") + EXTRA2.get("keji-fangzhi", "")) or _OLD.get("keji-fangzhi", "")), None, {'type': 'object', 'params': {'kind': 'silkroad', 'label': None}}, ['丝织', '丝绸', '工艺'])
E('diji-jiuzhou', "九州与禹贡", "地理·民族·军事", "疆域山川", "《尚书·禹贡》划定的天下蓝图。", ((BODIES.get("diji-jiuzhou", "") + EXTRA.get("diji-jiuzhou", "") + EXTRA2.get("diji-jiuzhou", "")) or _OLD.get("diji-jiuzhou", "")), [{'lib': '禹贡', 'id': 'yg-1'}], {'type': 'character', 'params': {'char': '州', 'seal': False}}, ['九州', '禹贡', '地理'])
E('diji-jianghe', "黄河长江", "地理·民族·军事", "疆域山川", "哺育文明的两河，定义中国的南北。", ((BODIES.get("diji-jianghe", "") + EXTRA.get("diji-jianghe", "") + EXTRA2.get("diji-jianghe", "")) or _OLD.get("diji-jianghe", "")), [{'lib': '水经注', 'id': 'sj-2'}], {'type': 'character', 'params': {'char': '川', 'seal': False}}, ['黄河', '长江', '山川'])
E('diji-dayunhe', "大运河", "地理·民族·军事", "交通驿传", "贯通南北的人工输血管。", ((BODIES.get("diji-dayunhe", "") + EXTRA.get("diji-dayunhe", "") + EXTRA2.get("diji-dayunhe", "")) or _OLD.get("diji-dayunhe", "")), None, {'type': 'character', 'params': {'char': '运', 'seal': False}}, ['大运河', '漕运', '交通'])
E('diji-sichou', "丝绸之路", "地理·民族·军事", "交通驿传", "横贯欧亚的文明交流大动脉。", ((BODIES.get("diji-sichou", "") + EXTRA.get("diji-sichou", "") + EXTRA2.get("diji-sichou", "")) or _OLD.get("diji-sichou", "")), None, {'type': 'object', 'params': {'kind': 'silkroad', 'label': None}}, ['丝绸之路', '贸易', '交通'])
E('diji-minzu', "华夏与民族", "地理·民族·军事", "民族交融", "以文化而非血统界定的认同。", ((BODIES.get("diji-minzu", "") + EXTRA.get("diji-minzu", "") + EXTRA2.get("diji-minzu", "")) or _OLD.get("diji-minzu", "")), [{'lib': '禹贡', 'id': 'yg-2'}], {'type': 'character', 'params': {'char': '华', 'seal': False}}, ['民族', '华夏', '融合'])
E('diji-chama', "茶马古道", "地理·民族·军事", "民族交融", "以叶换蹄的西南命脉。", ((BODIES.get("diji-chama", "") + EXTRA.get("diji-chama", "") + EXTRA2.get("diji-chama", "")) or _OLD.get("diji-chama", "")), [{'lib': '茶经', 'id': 'cj-1'}], {'type': 'character', 'params': {'char': '茶', 'seal': False}}, ['茶马古道', '民族', '贸易'])
E('diji-bingzhi', "兵制演变", "地理·民族·军事", "兵制战事", "兵从哪来、听谁指挥的千古难题。", ((BODIES.get("diji-bingzhi", "") + EXTRA.get("diji-bingzhi", "") + EXTRA2.get("diji-bingzhi", "")) or _OLD.get("diji-bingzhi", "")), None, {'type': 'character', 'params': {'char': '兵', 'seal': False}}, ['兵制', '军制', '军事'])
E('diji-zhanyi', "著名战役", "地理·民族·军事", "兵制战事", "长平、赤壁、淝水：历史的转折手。", ((BODIES.get("diji-zhanyi", "") + EXTRA.get("diji-zhanyi", "") + EXTRA2.get("diji-zhanyi", "")) or _OLD.get("diji-zhanyi", "")), [{'lib': '史记', 'id': 'shiji-2'}], {'type': 'character', 'params': {'char': '战', 'seal': False}}, ['战役', '军事', '历史'])
E('diji-sunzi', "孙子兵法与谋略", "地理·民族·军事", "兵制战事", "不战而屈人之兵的全胜之道。", ((BODIES.get("diji-sunzi", "") + EXTRA.get("diji-sunzi", "") + EXTRA2.get("diji-sunzi", "")) or _OLD.get("diji-sunzi", "")), [{'lib': '孙子兵法', 'id': 'szbf-1'}], {'type': 'character', 'params': {'char': '谋', 'seal': False}}, ['孙子', '兵法', '谋略'])
E('diji-bingqi', "城防与兵器", "地理·民族·军事", "兵制战事", "攻与守的反复较量。", ((BODIES.get("diji-bingqi", "") + EXTRA.get("diji-bingqi", "") + EXTRA2.get("diji-bingqi", "")) or _OLD.get("diji-bingqi", "")), None, {'type': 'object', 'params': {'kind': 'greatwall', 'label': None}}, ['城防', '兵器', '军事'])
E('diji-yizhan', "驿传与交通", "地理·民族·军事", "交通驿传", "没有电讯时代的「信息基础设施」。", ((BODIES.get("diji-yizhan", "") + EXTRA.get("diji-yizhan", "") + EXTRA2.get("diji-yizhan", "")) or _OLD.get("diji-yizhan", "")), None, {'type': 'character', 'params': {'char': '驿', 'seal': False}}, ['驿传', '邮传', '交通'])
E('diji-jiangyu', "疆域变迁", "地理·民族·军事", "疆域山川", "随国力与族群消长而伸缩的版图。", ((BODIES.get("diji-jiangyu", "") + EXTRA.get("diji-jiangyu", "") + EXTRA2.get("diji-jiangyu", "")) or _OLD.get("diji-jiangyu", "")), [{'lib': '禹贡', 'id': 'yg-2'}], {'type': 'character', 'params': {'char': '疆', 'seal': False}}, ['疆域', '地理', '历史'])
E('diji-fangyan', "方言地理", "地理·民族·军事", "疆域山川", "地上的声音化石，活着的汉语史。", ((BODIES.get("diji-fangyan", "") + EXTRA.get("diji-fangyan", "") + EXTRA2.get("diji-fangyan", "")) or _OLD.get("diji-fangyan", "")), None, {'type': 'character', 'params': {'char': '言', 'seal': False}}, ['方言', '地理', '语言'])
E('diji-diming', "地名文化", "地理·民族·军事", "疆域山川", "刻在大地上的微缩方志。", ((BODIES.get("diji-diming", "") + EXTRA.get("diji-diming", "") + EXTRA2.get("diji-diming", "")) or _OLD.get("diji-diming", "")), None, {'type': 'character', 'params': {'char': '名', 'seal': False}}, ['地名', '文化', '地理'])


# ============ 写出 entries.json ============
dist = collections.Counter(e['domain'] for e in entries)
empty = [e["id"] for e in entries if not e["body"]]
json.dump({"entries": entries}, open("data/entries.json", "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("条目总数:", len(entries))
print('各领域分布:', dict(dist))
print("使用旧正文(待写厚)的条目数:", len(empty))